### PR TITLE
Dlp fixes

### LINKED ISSUE #116: DLP UI links
- Link from Dandiset Landing Page to contents of the dandiset with some UI element
- Link from the contents view to the DLP with some UI element

### LINKED ISSUE #117: DLP tune up
Top block: name, permalink, and identifier. Remove the top right block that currently has the identifier, as we are moving identifier to the top block.

Permalink, for now is only for drafts (née staging) because we don't yet have releases.

e.g. `https://dandiarchive.org/dandiset/000001/draft`

Then middle block is as is (though we may want to update these values from something we calculate, at some point).

Then bottom block shows all other key/values. It can be displayed as it currently is, but just showing all key values of the dandiset-metadata.yaml.

Screen Shot 2020-03-03 at 6 56 24 PM

### PR DESCRIPTION
**Pull request by AlmightyYakob**
Fixes #117.
Fixes #116.

I've added some additional logic with the `fetchFullLocation` function. This is to allow for the button that links from the dandiset contents to the dandiset landing page to function properly, as to appear it needs to know if the folder is a valid dandiset or not.

### CODE REVIEW

File: web/src/views/DandiMetaViewer.vue [hunk 1]
```diff
@@ -29,7 +29,27 @@
...
+                    <v-btn icon>
+                      <v-icon>mdi-content-copy</v-icon>
+                    </v-btn>
+                  </v-list-item-action>
+                  <v-spacer /> -->
+                </v-list-item>
+                <v-list-item>
+                  <v-list-item-content>
+                    <a :href="`https://dandiarchive.org/dandiset/${meta.identifier}/draft`">
+                      {{ `https://dandiarchive.org/dandiset/${meta.identifier}/draft` }}
```
Comment (zachmullen) [inline web/src/views/DandiMetaViewer.vue]: I'm not sure how many places this base URL `https://dandiarchive.org` is hard-coded, but I'd be more comfortable if we used a variable for it.

File: web/src/views/DandiMetaViewer.vue [hunk 2]
```diff
@@ -76,26 +102,22 @@
                     <v-list-item-content>{{item}}</v-list-item-content>
                   </v-list-item>
                 </template>
+                <template v-for="(item, k) in extraFields">
+                  <v-subheader :key="k">{{ k }}</v-subheader>
+                  <v-list-item :key="k">
+                    <v-list-item-content>
+                      <template v-if="['object', 'array'].includes(schema.properties[k].type)">
+                        <vue-json-pretty :data="item" highlightMouseoverNode />
```
Comment (zachmullen) [inline web/src/views/DandiMetaViewer.vue]: Aren't props usually passed as e.g. `highlight-mouseover-node`? Or is my Vue-fu just stale?

File: web/src/views/DandiMetaViewer.vue [hunk 3]
```diff
@@ -42,9 +62,15 @@
                 >
                   <v-icon>mdi-pencil</v-icon>
                 </v-btn>
+                <v-btn
+                  @click="viewContents"
```
Comment (zachmullen) [inline web/src/views/DandiMetaViewer.vue]: In general if a button's purpose is to link to a URL, we should use `:to` rather than `@click`. This allows the user to interact with the link: preview the URL, open it in a new tab, copy the URL, etc.

File: web/src/views/Home.vue [hunk 4]
```diff
@@ -35,24 +47,35 @@ import {
...
 ];
 
 export default {
   components: { GirderDataDetails, GirderFileManager },
   computed: {
+    isDandiset() {
+      return (
+        !!this.location
+        && !!this.location.meta
+        && !!this.location.meta.dandiset
```
Comment (zachmullen) [inline web/src/views/Home.vue]: To save on both punctuation and time, we can just do

```javascript
!!(this.location && this.location.meta && this.location.meta.dandiset)
```

And hold out hope for the [null propagation operator](https://ponyfoo.com/articles/null-propagation-operator).

File: web/src/views/Home.vue [hunk 5]
```diff
@@ -3,13 +3,20 @@
...
+          :selectable="true"
+          :location.sync="location"
+          :upload-enabled="false"
+          :value="selected"
+          @input="setSelected"
+          :initial-items-per-page="25"
+          :items-per-page-options="[10,25,50,100,-1]"
+        >
+          <template v-slot:headerwidget v-if="isDandiset">
+            <v-btn icon color="primary" @click="viewDandiset">
```
Comment (zachmullen) [inline web/src/views/Home.vue]: Same here, use `:to` rather than `@click`

File: web/src/views/Home.vue (hunk 4 above)
Comment (AlmightyYakob) [reply web/src/views/Home.vue]: Good point. Can't wait to be using the "Elvis" operator.

File: web/src/views/DandiMetaViewer.vue (hunk 3 above)
Comment (AlmightyYakob) [reply web/src/views/DandiMetaViewer.vue]: Good to know, I'll fix it!

File: web/src/views/DandiMetaViewer.vue (hunk 2 above)
Comment (AlmightyYakob) [reply web/src/views/DandiMetaViewer.vue]: Nope your Vue-fu is still good

File: web/src/utils.js [hunk 6]
```diff
@@ -1,3 +1,5 @@
+const rootDandiUrl = 'dandiarchive.org';
```
Comment (zachmullen) [inline web/src/utils.js]: While I'm sure it'll always be https, let's change this to be `https://dandiarchive.org`.

Comment (AlmightyYakob) [reply web/src/utils.js]: The reason I originally did it this way was to allow for subdomains like `hub.dandiarchive.org` and `girder.dandiarchive.org`, but I've updated it.

Comment (zachmullen) [reply web/src/utils.js]: If we get subdomains, I'd say those should just be entirely separate variables. This is the sort of thing that I'd normally use `process.env` for so that the application is agnostic (to whatever extent possible) to its deployed environment.

File: web/src/views/DandiMetaViewer.vue [hunk 7]
```diff
@@ -29,7 +29,27 @@
...
+                    <a :href="permalink">
+                      {{ permalink }}
+                    </a>
+                  </v-list-item-content>
+                </v-list-item>
+              </v-list>
+              <v-card-actions class="py-0">
                 <v-btn
                   icon
                   @click="$router.push(`/collection/${selected.parentId}`)"
```
Comment (zachmullen) [inline web/src/views/DandiMetaViewer.vue]: I realize this isn't part of this PR but since we are already doing this, let's go ahead and replace `@click` with `:to` here.

**Comment by AlmightyYakob** [comment]
@zachmullen should be good to go
