### PR TITLE
Fix contributor list filtering

### LINKED ISSUE #912: erroneous entity listed in contributor section
for this dandiset (https://dandiarchive.org/dandiset/000026/draft), the last person listed in contributors has `false` for `includeInCitation`

### PR DESCRIPTION
**Pull request by mvandenburgh**
This bit of code somehow got lost when I implemented the redesign. I think there's a lot of improvements that can be made to the code (to make it work with TypeScript, but also in general), but I don't think it's worth spending time on because this component will go away in the near future anyways.

Fixes #912

### CODE REVIEW

File: src/views/DandisetLandingView/DandisetContributors.vue [hunk 1]
```diff
@@ -42,16 +46,38 @@
...
+          let orcid_id = author.identifier;
+          if ((author.affiliation as any)?.length) {
+            affiliations = (author.affiliation as any).map((a: any) => a.name).join(', ');
+          }
+          let author_name = author.name;
+          if (index < persons.length - 1) {
+            author_name = `${author.name};`;
+          }
+          if (orcid_id) {
+            orcid_id = `https://orcid.org/${orcid_id}`;
```
Comment (satra) [inline src/views/DandisetLandingView/DandisetContributors.vue:74]: if this is being done then the template `:href` that displays it needs to change back
